version: '3.8'

services:
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      networks:
        - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DB_ADDR=url_shortner-redis-1:6379
      - DB_PASS=
      - REDIS_URL=redis:6379
      - DOMAIN=http://localhost:3000
      - API_QUOTA=1000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
